//! Kodi `advancedsettings.xml` generator — pure (commitment #1: no I/O).
//!
//! Produces an `advancedsettings.xml` override string the user imports into
//! Kodi's userdata dir. `advancedsettings.xml` is a read-only-to-Kodi override
//! (unlike `guisettings.xml`, which Kodi rewrites on exit), so it's the safe
//! file to generate. The host (commands/media_apps.rs) stages the string to the
//! device; this module only builds it. Setting ids are from the Kodi wiki.

use serde::{Deserialize, Serialize};

/// When Kodi switches the display refresh rate to match video fps
/// (`videoplayer.adjustrefreshrate`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AdjustRefreshRate {
    /// 0 — never switch.
    Off,
    /// 1 — always switch (recommended for a Shield on a fixed-rate panel).
    Always,
    /// 2 — switch on start and stop.
    OnStartStop,
    /// 3 — switch on start only.
    OnStart,
}

impl AdjustRefreshRate {
    fn value(self) -> u8 {
        match self {
            AdjustRefreshRate::Off => 0,
            AdjustRefreshRate::Always => 1,
            AdjustRefreshRate::OnStartStop => 2,
            AdjustRefreshRate::OnStart => 3,
        }
    }
}

/// User-chosen Kodi tuning, mirrored by `KodiProfile` in `src/lib/types.ts`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KodiProfile {
    pub adjust_refresh_rate: AdjustRefreshRate,
    /// `videoplayer.usedisplayasclock` — sync playback to the display clock.
    pub sync_playback_to_display: bool,
    /// `winsystem.ishdrdisplay` — let Kodi use the panel's HDR/DV capability.
    pub hdr_display: bool,
    /// `audiooutput.passthrough` — master passthrough switch.
    pub passthrough: bool,
    pub ac3_passthrough: bool,
    pub eac3_passthrough: bool,
    pub dts_passthrough: bool,
    pub truehd_passthrough: bool,
    pub dtshd_passthrough: bool,
    /// `audiooutput.ac3transcode` — transcode multichannel to AC-3 for ARC/optical.
    pub ac3_transcode: bool,
    /// Allowed display modes, e.g. `"3840x2160@24.000000"`. Empty = no whitelist.
    pub resolution_whitelist: Vec<String>,
    /// `videoscreen.whitelistpulldown` — allow 3:2 pulldown rates.
    pub whitelist_pulldown: bool,
    /// `videoscreen.whitelistdoublerefreshrate` — allow doubled rates (25→50).
    pub whitelist_double_refresh: bool,
}

fn b(v: bool) -> &'static str {
    if v {
        "true"
    } else {
        "false"
    }
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Render the `advancedsettings.xml` for `profile`.
pub fn render_advancedsettings(profile: &KodiProfile) -> String {
    let mut out = String::new();
    out.push_str("<!-- Generated by Shield Optimizer. Import into Kodi userdata. -->\n");
    out.push_str("<advancedsettings>\n");

    out.push_str("  <videoplayer>\n");
    out.push_str(&format!(
        "    <adjustrefreshrate>{}</adjustrefreshrate>\n",
        profile.adjust_refresh_rate.value()
    ));
    out.push_str(&format!(
        "    <usedisplayasclock>{}</usedisplayasclock>\n",
        b(profile.sync_playback_to_display)
    ));
    out.push_str("  </videoplayer>\n");

    out.push_str("  <winsystem>\n");
    out.push_str(&format!(
        "    <ishdrdisplay>{}</ishdrdisplay>\n",
        b(profile.hdr_display)
    ));
    out.push_str("  </winsystem>\n");

    out.push_str("  <audiooutput>\n");
    out.push_str(&format!(
        "    <passthrough>{}</passthrough>\n",
        b(profile.passthrough)
    ));
    out.push_str(&format!(
        "    <ac3passthrough>{}</ac3passthrough>\n",
        b(profile.ac3_passthrough)
    ));
    out.push_str(&format!(
        "    <eac3passthrough>{}</eac3passthrough>\n",
        b(profile.eac3_passthrough)
    ));
    out.push_str(&format!(
        "    <dtspassthrough>{}</dtspassthrough>\n",
        b(profile.dts_passthrough)
    ));
    out.push_str(&format!(
        "    <truehdpassthrough>{}</truehdpassthrough>\n",
        b(profile.truehd_passthrough)
    ));
    out.push_str(&format!(
        "    <dtshdpassthrough>{}</dtshdpassthrough>\n",
        b(profile.dtshd_passthrough)
    ));
    out.push_str(&format!(
        "    <ac3transcode>{}</ac3transcode>\n",
        b(profile.ac3_transcode)
    ));
    out.push_str("  </audiooutput>\n");

    if !profile.resolution_whitelist.is_empty() {
        out.push_str("  <videoscreen>\n");
        for res in &profile.resolution_whitelist {
            out.push_str(&format!("    <whitelist>{}</whitelist>\n", xml_escape(res)));
        }
        out.push_str(&format!(
            "    <whitelistpulldown>{}</whitelistpulldown>\n",
            b(profile.whitelist_pulldown)
        ));
        out.push_str(&format!(
            "    <whitelistdoublerefreshrate>{}</whitelistdoublerefreshrate>\n",
            b(profile.whitelist_double_refresh)
        ));
        out.push_str("  </videoscreen>\n");
    }

    out.push_str("</advancedsettings>\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn profile() -> KodiProfile {
        KodiProfile {
            adjust_refresh_rate: AdjustRefreshRate::Always,
            sync_playback_to_display: true,
            hdr_display: true,
            passthrough: true,
            ac3_passthrough: true,
            eac3_passthrough: true,
            dts_passthrough: true,
            truehd_passthrough: false,
            dtshd_passthrough: false,
            ac3_transcode: false,
            resolution_whitelist: vec![],
            whitelist_pulldown: false,
            whitelist_double_refresh: false,
        }
    }

    #[test]
    fn renders_core_audio_and_video_sections() {
        let xml = render_advancedsettings(&profile());
        assert!(xml.starts_with("<!-- Generated"));
        assert!(xml.contains("<adjustrefreshrate>1</adjustrefreshrate>"));
        assert!(xml.contains("<ishdrdisplay>true</ishdrdisplay>"));
        assert!(xml.contains("<passthrough>true</passthrough>"));
        assert!(xml.contains("<truehdpassthrough>false</truehdpassthrough>"));
        assert!(xml.contains("<ac3transcode>false</ac3transcode>"));
        assert!(xml.trim_end().ends_with("</advancedsettings>"));
    }

    #[test]
    fn omits_videoscreen_when_no_whitelist() {
        let xml = render_advancedsettings(&profile());
        assert!(!xml.contains("<videoscreen>"));
    }

    #[test]
    fn emits_and_escapes_whitelist_entries() {
        let mut p = profile();
        p.resolution_whitelist = vec!["3840x2160@24.000000".into(), "1920x1080@50.000000".into()];
        p.whitelist_double_refresh = true;
        let xml = render_advancedsettings(&p);
        assert!(xml.contains("<videoscreen>"));
        assert!(xml.contains("<whitelist>3840x2160@24.000000</whitelist>"));
        assert!(xml.contains("<whitelistdoublerefreshrate>true</whitelistdoublerefreshrate>"));
    }

    #[test]
    fn refresh_rate_values_map_correctly() {
        assert_eq!(AdjustRefreshRate::Off.value(), 0);
        assert_eq!(AdjustRefreshRate::Always.value(), 1);
        assert_eq!(AdjustRefreshRate::OnStartStop.value(), 2);
        assert_eq!(AdjustRefreshRate::OnStart.value(), 3);
    }
}
